# Method script for fetching data from the CBioPortal.
# Author: Philemon Schoepf <philemon.schoepf@student.ubik.ac.at>
# Date: 2021-03-19

# Imports -----------------------------------------------------------------
#' @import cBioPortalData org.Hs.eg.db dplyr
# placeholder import to force presence of AnnotationDbi package, we actually need "select" function but this clashes with dplyr
#' @importFrom AnnotationDbi GOTerms
#' @importFrom httr parse_url
#' @importFrom purrr map map_chr pmap reduce
#' @importFrom S4Vectors isEmpty
#' @importFrom stats na.omit
#' @importFrom stringr str_starts str_detect str_to_sentence
#' @importFrom tibble tibble
#' @importFrom tidyr pivot_wider
NULL

# Global Variables --------------------------------------------------------

# Study IDs of cell line studies in cBioPortal. Should not change often.
CELL_LINE_STUDIES = c("cellline_nci60",
                      "cellline_ccle_broad",
                      "ccle_broad_2019")

# Helper Functions --------------------------------------------------------

#' Convert a cBioPortal query URL into a list of studies.
#'
#' @description Extracts the studyIds from a cBioPortal URL. This enables use of the web GUI for study selection by exporting the URLs.
#' This is intended to be used with patient data only, for the cell lines the study IDs are provided as constants.
#'
#' @param url a URL generated by a cBioPortal query
#'
#' @return a vector of studyIds
#'
#' @examples \dontrun{
#' studyList <- getStudiesFromUrl("https://www.cbioportal.org/results/
#' download?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=
#' all_stjude_2015%2Call_stjude_2016%2Clcll_broad_2013%2Ccll_broad_2015%2C
#' all_phase2_target_2018_pub%2Cpcnsl_mayo_2015&case_set_id=all&
#' data_priority=0&gene_list=MYC%2520BASP1%2520PHB&
#' geneset_list=%20&profileFilter=0&tab_index=tab_visualize")
#' }
#'
getStudiesFromUrl <- function(url) {

  cancerStudyString <- parse_url(url)$query$cancer_study_list
  cancerStudiesAsVector <- cancerStudyString %>% strsplit(",") %>% unlist()
  return(cancerStudiesAsVector)

}

#' Make a translation table between HUGO and EntrezID.
#'
#' @description The cBioPortal API internally uses Entrez IDs, which are not
#' very human-readable. Therefore this function take a given list of HUGO
#' gene symbols and turns it into a lookup table to use in other functions.
#'
#' @param genelist A numerical or character vector of genes. Accepted are HUGO
#' and EntrezId.
#'
#' @return A dataframe whith HUGO and EntrezId for each gene
#'
#' @examples \dontrun{
#' tranlatedGenes <- translateGenes(C("MYC", "BASP1", "MTOR", "RPTOR"))
#' }
#'
translateGenes <- function (genelist) {
  #if all genes are numerical, i.e. Entrez, convert to Hugo
  if(all(str_detect(genelist, "[0-9]+"))) {
    return(AnnotationDbi::select(org.Hs.eg.db,
                                 keys = genelist,
                                 column = "SYMBOL",
                                 keytype = "ENTREZID"))
  }
  else if(all(str_detect(genelist, "[a-zA-Z]+"))) {
    return(AnnotationDbi::select(org.Hs.eg.db,
                                 keys = genelist,
                                 column = "ENTREZID",
                                 keytype = "SYMBOL"))
  }
}


#' Convert a HUGO symbol to Entrez ID.
#'
#' @description Converts a HUGO gene symbol to Entrez using org.Hs.eg.db.
#' Returns identity if it is already a Entrez symbol.
#'
#' @param gene Either a HUGO gene symbol string or a Entrez ID
#' @param translatorTable A translator table generated by translateGenes
#'
#' @return A Entrez Id
#'
#' @examples \dontrun{
#' translatedGenes <- translateGenes(c("MYC", "MTOR")
#' toEntrez("MYC")
#' toEntrez("MTOR")
#' toEntrez(4609)
#' toEntrez("4609")
#' }
toEntrez <- function(gene, translatorTable = translatedGenes) {

  (translatorTable %>% filter(ENTREZID == gene | SYMBOL == gene))$ENTREZID
}


#' Convert a Entrez ID to HUGO.
#'
#' @description Converts a Entrez Id to HUGO using org.Hs.eg.db.
#' Returns identity if it is already a HUGO symbol.
#'
#' @param gene Either a HUGO gene symbol string or a Entrez ID
#' @param translatorTable A translator table generated by translateGenes
#'
#' @return A HUGO symbol
#'
#' @examples \dontrun{
#' translatedGenes <- translateGenes(c("MYC", "MTOR"))
#' toHugo("MYC")
#' toHugo(4609)
#' toHugo("4609")
#' }
toHugo <- function(gene, translatorTable = translatedGenes) {

  (translatorTable %>% filter(ENTREZID == gene | SYMBOL == gene))$SYMBOL

}


#' Get expression data from a single study.
#'
#' @description gets RNA expression profiles from cBioPortal for the given study and genes
#'
#' @param study A studyId string, e.g. "ccle_broad_2019"
#' @param genes A character vector of HUGO gene names
#' @param molecularProfile A molecularProfile stub to search for. Usually "rna_seq_v2_mrna" or similar
#'
#' @return A table of expression values as given by cBioPortalData
#'
#' @examples \dontrun{
#' moldata <- getMolecularData("ccle_broad_2019", c("MYC", "BASP1"), "rna_seq_mrna")
#' }
#'
#' @export
getMolecularData <- function(study, genes, molecularProfile) {
  # list all sampleIds from the study
  samples <- allSamples(cbio, studyId = study)

  # get mRNA expression molecular profiles, or empty tibble if there are no data
  rnaProfiles <-
    molecularProfiles(cbio, studyId = study) %>%
    select(molecularProfileId) %>%
    filter(str_detect(molecularProfileId, paste0(molecularProfile, "$")))

  # return empty tibble if no expression profile was found
  if (isEmpty(rnaProfiles$molecularProfileId)) {
    return(tibble())
  }

  return(
    molecularData(
      api = cbio,
      molecularProfileIds = rnaProfiles$molecularProfileId,
      entrezGeneIds = map_chr(genes, toEntrez),
      sampleIds = samples$sampleId
    )[[1]]
  )

}

#' Make a table of RNA expression values.
#'
#' @param studyList List of studies
#' @param genes Character vector of genes to evaluate
#' @param molecularProfile The type of molecular profile to query. For most
#' patient cohorts it is "rna_seq_v2_mrna", for cell lines "rna_seq_mrna".
#'
#' @return A tibble of RNA expression values, grouped by cancer origin,
#' one row per sample.
#'
#' @export
makeExpressionTable <- function(studyList, genes, molecularProfile) {

  expressions.longtable <- reduce(map(studyList, getMolecularData,
                                             genes = genes,
                                             molecularProfile = molecularProfile),
                                         rbind)

  # remove NA and restructure output
  expressions.widetable <- expressions.longtable %>%
    select(studyId, sampleId, entrezGeneId, value) %>%
    pivot_wider(names_from = entrezGeneId, values_from = value) %>%
    na.omit() %>%
    rename_with(.fn = map_chr, .f = toHugo, .cols = matches("[0-9]+"))

  return(expressions.widetable)
}


#' Make an expression table for multiple cancer types.
#'
#' @description A table of cancer types and their respecitve studies
#' (as character vector or raw cbioPortal URL) is searched and output in a table
#' grouped by cancer origin.
#'
#' @param inputTable A 2-column dataframe, colnames have to be "origin" and "studies".
#' @param genes Character vector of genes to evaluate
#' @param molecularProfile The type of molecular profile to query. For most
#' patient cohorts it is "rna_seq_v2_mrna", for cell lines "rna_seq_mrna".
#'
#' @return A tibble of RNA expression values, grouped by cancer origin,
#'one row per sample.
#'
#' @examples \dontrun{
#' allPatientData <- combineMultipleCancerTypes(table, c("MTOR", "RPTOR"), "rna_seq_v2_mrna")
#' }
#'
#' @export
combineMultipleCancerTypes <- function(inputTable, genes, molecularProfile) {

  # Helper function to process 1 line of input
  annotateOrigins <- function(origin, studies, ...) {

    # if a URL is supplied, convert it to a list of studies
    if(str_starts(studies, "http")) {
     studies <- getStudiesFromUrl(studies)
    }
    expressionTable <- makeExpressionTable(studies, genes, molecularProfile) %>%
      mutate(origin = origin)
    return(expressionTable)
  }

  all.patient.expressions <- reduce(pmap(inputTable, .f = annotateOrigins), rbind) %>%
    group_by(origin) %>%
    mutate(n = n(), originWithN = paste0(origin, " (n = ", n, ")"))
  return(all.patient.expressions)
}

#' Filter cBioPortal data by cancer origin.
#'
#' @param expressionData A Tibble containing the expression data
#' @param filterList A character vector containing the cancer types to filter
#' @param column Column name to filter by. Default is "origin".
#'
#' @return Tibble of filtered expression data
#'
#' @examples \dontrun{
#' filterByOrigin(allPatientData, c("Bowel", "Breast", "Melanoma"))
#' }
#'
filterByOrigin <- function(expressionData, filterList, column = origin) {
  filterString <- paste(filterList, collapse = "|")

  filter(expressionData, grepl(filterString, {{column}}, ignore.case = T))

}

# Main function ------------------------------------------------------


#' Generate expression table for a set of genes.
#'
#' @param gene1 "Numerator" gene.
#' @param gene2 "Denominator" gene.
#' @param ... more optional genes
#'
#' @return Writes tibbles "filteredPatientData", "filteredCellData", and
#' "selectedCellData" to a global variable.
#'
#' @examples \dontrun{
#' fetchCbioData("MYC", "BASP1")
#' }
#'
#' @export
fetchCbioData <- function(gene1, gene2, ...) {

  # Create a CBioPortal API client
  cbio <<- cBioPortal()

  # set up gene table
  selGenes <<- c(gene1, gene2, ...)
  translatedGenes <<- translateGenes(selGenes)

  allPatientData <- combineMultipleCancerTypes(patientUrls, selGenes, "rna_seq_v2_mrna")
  allCellData <- makeExpressionTable(CELL_LINE_STUDIES, selGenes, "rna_seq_mrna") %>%
    mutate(origin = gsub("^.*?_", "", sampleId)) %>%
    group_by(origin)

  filteredPatientData <<- filterByOrigin(allPatientData, patientFilter)

  filteredCellData <<- filterByOrigin(allCellData, cellFilter) %>%
    # remove some ugliness from the cell names
    mutate(origin = gsub("HAEMATOPOIETIC_AND_LYMPHOID_TISSUE", "HAEMATOPOIETIC/LYMPHOID_TISSUE", origin)) %>%
    mutate(origin = gsub("_", " ", str_to_sentence(origin)),
           n = n(),
           originWithN = paste0(origin, " (n = ", n, ")"))

  selectedCellData <<- filterByOrigin(filteredCellData, selectedCellFilter, sampleId) %>%
    mutate(Name = gsub("_.*", "", sampleId, ignore.case = T)) %>%
    ungroup()

  # List of studies used to generate data
  listOfStudies <<- allPatientData$studyId %>% unique()

}
