# Method script for downloading data from the cBioPortal API.
# @author Philemon Schöpf <philemon.schoepf@student.ubik.ac.at>

library(tibble)
library(cBioPortalData)
library(AnVIL)
library(org.Hs.eg.db)
library(dplyr)
library(httr)
library(stringr)

# Study IDs of cell line studies in cBioPortal.
# Should not change often, therefore hardcoded here.
CELL_LINE_STUDIES = c("cellline_nci60",
                      "cellline_ccle_broad",
                      "ccle_broad_2019"
                      )

# Create a CBioPortal API client
cbio <- cBioPortal()


#' getStudiesFromUrl
#'
#' @description Extracts the studyIds from a cBioPortal URL. This enables use of the web GUI for study selection by exporting the URLs.
#' This is intended to be used with patient data only, for the cell lines the study IDs are provided as constants.
#' 
#' @param url a URL generated by a cBioPortal query
#'
#' @return a vector of studyIds
#' @export
#'
#' @examples
getStudiesFromUrl <- function(url) {
  
  cancerStudyString <- httr::parse_url(url)$query$cancer_study_list
  cancerStudiesAsVector <- cancerStudyString %>% strsplit(",")
  return(cancerStudiesAsVector)
  
}

#' toEntrez
#' 
#' @description Converts a HUGO gene symbol to Entrez using org.Hs.eg.db.
#' Returns identity if it is already a Entrez symbol.
#'
#' @param gene Either a HUGO gene symbol string or a Entrez ID
#'
#' @return A Entrez Id
#'
#' @examples 
#' translate("MYC")
#' translate(4609)
#' translate("4609")
toEntrez <- function(gene) {
  
  # AnnotationDbi only handles strings
  gene <- toString(gene) 
  
  if(!str_starts(gene, "[0-9]")) {
    gene <- AnnotationDbi::select(org.Hs.eg.db, keys = gene, column = "ENTREZID", keytype = "SYMBOL")$ENTREZID
  }
  
  # convert back to int
  return(strtoi(gene))
}


#' toHugo
#' 
#' @description Converts a Entrez Id to HUGO using org.Hs.eg.db.
#' Returns identity if it is already a HUGO symbol.
#'
#' @param gene Either a HUGO gene symbol string or a Entrez ID
#'
#' @return A HUGO symbol.
#'
#' @examples 
#' translate("MYC")
#' translate(4609)
#' translate("4609")
toHugo <- function(gene) {
  
  # AnnotationDbi only handles strings
  gene <- toString(gene) 
  
  if(str_starts(gene, "[0-9]")) {
    gene <- AnnotationDbi::select(org.Hs.eg.db, keys = gene, column = "SYMBOL", keytype = "ENTREZID")$SYMBOL
  }
  
  return(gene)
}


#' getMolecularData
#' 
#' @description gets RNA expression profiles from cBioPortal for the given study and genes
#'
#' @param study a studyId string, e.g. "ccle_broad_2019"
#' @param molecularProfile 
#'
#' @return
#' @export
#'
#' @examples
getMolecularData <- function(study, molecularProfile) {
  # list all sampleIds from the study
  samples <- cBioPortalData::allSamples(cbio, studyId = study)
  
  # get mRNA expression molecular profiles, or empty tibble if there are no data
  rnaProfiles <-
    molecularProfiles(cbio, studyId = study, projection = "ID") %>%
    filter(str_detect(molecularProfileId, paste0("_", molecularProfile, "$")))
  
  #return if no RNA expression profile exists
  if (!isEmpty(rnaProfiles$molecularProfileId)) {
    return(
      molecularData(
        api = cbio,
        molecularProfileIds = rnaProfiles$molecularProfileId,
        entrezGeneIds = unlist(lapply(selGenes, toEntrez)),
        sampleIds = samples$sampleId
      )
    )
  }
  else {
    return(NULL)
  }
}

#################
# main function #
#################
fetchPat <- function(url, selGenes) {
  translatorTable <- generateTranslatorTable(selGenes)
  selStudyList <- getStudiesFromUrl(url)
  
  # get data from all selected studies
  all.data <- tibble()
  for (study in selStudyList) {
    new.data <- getMolecularData(study, molecularProfile = "rna_seq_v2_mrna", translatorTable =  translatorTable)
    all.data <- rbind(all.data, new.data[[1]])
  }
  # remove NA and restructure output
  wideOutput <- all.data %>%
    mutate(all.data, hugoGeneSymbol = sapply(X = entrezGeneId, FUN = translate, translatorTable)) %>%
    select(studyId, sampleId, hugoGeneSymbol, value) %>%
    pivot_wider(names_from = hugoGeneSymbol, values_from = value)
  return(wideOutput)
}

fetchCells <- function(url, selGenes) {
  translatorTable <- generateTranslatorTable(selGenes)
  selStudyList <- getStudiesFromUrl(url)
  
  # get data from all selected studies
  all.data <- tibble()
  for (study in selStudyList) {
    new.data <- getMolecularData(study, molecularProfile = "rna_seq_mrna", translatorTable = translatorTable)
    all.data <- rbind(all.data, new.data[[1]])
  }
  # restructure output table
  wideOutput <- all.data %>%
    na.omit() %>%
    mutate(all.data, hugoGeneSymbol = sapply(X = entrezGeneId, FUN = translate, translatorTable)) %>%
    select(studyId, sampleId, hugoGeneSymbol, value) %>%
    pivot_wider(names_from = hugoGeneSymbol, values_from = value)
  return(wideOutput)
}